# Generated by Django 4.2.16 on 2024-10-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Траектория',
                'verbose_name_plural': 'Траектории',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('coordinates', models.CharField(max_length=255, verbose_name='Координаты')),
                ('text_riddle', models.TextField(blank=True, null=True, verbose_name='Загадка при прибытии на место')),
                ('video_riddle_url', models.URLField(verbose_name='Видео загадка')),
                ('video_story_url', models.URLField(verbose_name='Видео с историей места')),
                ('task_file', models.FileField(upload_to='tasks/', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('contacts', models.TextField(max_length=255, verbose_name='Контакты для связи')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.path', verbose_name='Выбранная траектория')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='TeamPlaceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Время начала отгадывания места')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания отгадывания места')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото-подтверждение')),
                ('task_answer', models.TextField(blank=True, null=True, verbose_name='Ответ на задание')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.place', verbose_name='Место')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Ответы команды',
                'verbose_name_plural': 'Ответы команд',
            },
        ),
        migrations.CreateModel(
            name='PlaceInPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.path', verbose_name='Траектория')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Место в траектории',
                'verbose_name_plural': 'Места в траектории',
                'ordering': ['position'],
                'unique_together': {('place', 'path')},
            },
        ),
        migrations.AddField(
            model_name='path',
            name='places',
            field=models.ManyToManyField(through='backend.PlaceInPath', to='backend.place', verbose_name='Места'),
        ),
    ]
